### ISSUE TITLE
Quick Question Machnet capabilities

### ISSUE THREAD

**Issue by moscovium115** [microsoft/machnet#32]
Hello Developers,

I had a quick question. I was wondering if Machnet could be used to send and receive TCP requests to a certain URL? Are there any resources that can help me achieve my goal?

Thank you

**Comment by sarsanaee** [comment]
Hi @moscovium115 

Machnet is a transport engine; it is not a web server or client to send HTTP or TCP requests to a particular URL. You may interface with Machnet to send HTTP requests to a remote host. 

If you want to send HTTP requests, you may have your client use the [Machnet shared memory library](https://github.com/microsoft/machnet#machnet-api). You can also check the [msg-gen app](https://github.com/microsoft/machnet/tree/main/src/apps/msg_gen) to understand how to port applications to Machnet.

Further, Machnet implements a reliable transport. Thus, if your application uses Machnet, messages will be delivered in a lossless fashion.

Please let me know if you still have any questions.

Thanks,
Alireza

**Comment by moscovium115** [comment]
Thanks for the speedy and thorough answer. :) . Looks like I would have to learn more about what a TCP client does under the hood.

Will be closing the issue
